# Generated by Django 3.0.7 on 2024-05-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20240518_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='firstname',
            new_name='first_name',
        ),
    ]
