# Generated by Django 3.0.7 on 2024-05-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20240518_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
